services:
  postgres:
    image: postgres:16-alpine
    container_name: djassa_postgres
    restart: always
    environment:
      POSTGRES_USER: djassa_user
      POSTGRES_PASSWORD: djassa_secure_pass_2026
      POSTGRES_DB: djassa_db
    ports:
      - "5432:5432"
    volumes:
      - djassa_pg_data:/var/lib/postgresql/data

volumes:
  djassa_pg_data:
    driver: local
